// webpack and webpack cli might be needed
var webpack = require('webpack');
var path = require('path');
module.exports = {

    entry:{
        'index':'./src/index.js'
    },

    output:{
        // path ko resolve ani join hunchha
        path: path.resolve(__dirname, 'dist'),
        filename: 'main.js'
    },

    // loader
    module:{
        rules:[ // multiple rules
            { // iinside create different object
                // babel use garera es7,7 lai es5 ma lagna.... Browser Compatible garna
                //use babel on which files...(Sabai js file lai)
                test: /\.js$/, // Starts with duita slash (//) ani forward slash chai skip sequence 
                exclude: /node_modules/,
                use: 'babel-loader'
            }
        ]
    },
    // Dev server to serve the application, only in development
    devServer:{
        // Those content that are not generated by webpack
        contentBase: path.join(__dirname, "public/"),
        port: 3080,
        // to serve webpack files
        publicPath: "http://localhost:3080/dist/"
    }
}